services:
  - type: web
    name: lost-found-ai
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --extra-index-url https://download.pytorch.org/whl/cpu torch==2.0.1 torchvision==0.15.2
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: YOLO_CONFIG_DIR
        value: /tmp/Ultralytics

build:
  pythonVersion: 3.10